/**
 * IaC Code Generation Compiler (Terraform HCL & AWS CloudFormation)
 * Converts visual node graphs and configurations into deployable infrastructure code.
 */

/**
 * Clean string to valid HCL/YAML identifier
 */
function sanitizeName(name = '', fallback = 'resource') {
  const clean = name.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '');
  return clean || fallback;
}

/**
 * Generate Terraform HCL files (main.tf, variables.tf, outputs.tf)
 */
export function generateTerraformCode(nodes = [], edges = [], options = {}) {
  const region = options.region || 'us-east-1';
  const projectName = sanitizeName(options.projectName || 'infrasaas_app', 'infrasaas_app');

  let mainTf = `# ==============================================================================
# Terraform HCL Infrastructure Blueprint
# Auto-generated by InfraSaaS (https://infrasaas.app)
# Project: ${options.projectName || 'Cloud Architecture'}
# Provider: AWS (${region})
# ==============================================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

# ------------------------------------------------------------------------------
# VPC & Networking Baseline
# ------------------------------------------------------------------------------
resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name        = "${projectName}-vpc"
    Environment = "production"
    ManagedBy   = "InfraSaaS"
  }
}

resource "aws_subnet" "public_1" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "10.0.1.0/24"
  availability_zone       = "\${var.aws_region}a"
  map_public_ip_on_launch = true

  tags = {
    Name = "${projectName}-public-subnet-1"
  }
}

resource "aws_subnet" "private_1" {
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.10.0/24"
  availability_zone = "\${var.aws_region}a"

  tags = {
    Name = "${projectName}-private-subnet-1"
  }
}

resource "aws_internet_gateway" "gw" {
  vpc_id = aws_vpc.main.id

  tags = {
    Name = "${projectName}-igw"
  }
}

resource "aws_security_group" "app_sg" {
  name        = "${projectName}-app-sg"
  description = "Security group for application compute tier"
  vpc_id      = aws_vpc.main.id

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# ------------------------------------------------------------------------------
# Infrastructure Node Services
# ------------------------------------------------------------------------------
`;

  const outputs = [];

  nodes.forEach((node) => {
    if (node.type === 'client') return;

    const data = node.data || {};
    const config = data.config || {};
    const nodeType = data.type || '';
    const resId = sanitizeName(data.name || node.id, node.id);

    switch (nodeType) {
      case 'server':
      case 'vm': {
        const instType = config.instanceType || 't3.medium';
        const count = config.instances || 1;
        mainTf += `
# Compute Node: ${data.name || node.id}
resource "aws_instance" "${resId}" {
  count                  = ${count}
  ami                    = var.ubuntu_ami_id
  instance_type          = "${instType}"
  subnet_id              = aws_subnet.public_1.id
  vpc_security_group_ids = [aws_security_group.app_sg.id]

  root_block_device {
    volume_size           = 30
    volume_type           = "gp3"
    encrypted             = true
    delete_on_termination = true
  }

  tags = {
    Name        = "${data.name || node.id}-\${count.index + 1}"
    NodeType    = "${nodeType}"
    Environment = "production"
  }
}
`;
        outputs.push({
          name: `${resId}_ips`,
          value: `aws_instance.${resId}[*].public_ip`,
          desc: `Public IPs of ${data.name || node.id}`
        });
        break;
      }

      case 'container': {
        const tasks = config.taskCount || 2;
        mainTf += `
# Container Cluster: ${data.name || node.id}
resource "aws_ecs_cluster" "${resId}_cluster" {
  name = "${resId}-cluster"
}

resource "aws_ecs_task_definition" "${resId}_task" {
  family                   = "${resId}-task"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = 512
  memory                   = 1024

  container_definitions = jsonencode([
    {
      name      = "${resId}-app"
      image     = "nginx:alpine"
      essential = true
      portMappings = [
        {
          containerPort = 80
          hostPort      = 80
        }
      ]
    }
  ])
}

resource "aws_ecs_service" "${resId}_service" {
  name            = "${resId}-service"
  cluster         = aws_ecs_cluster.${resId}_cluster.id
  task_definition = aws_ecs_task_definition.${resId}_task.arn
  desired_count   = ${tasks}
  launch_type     = "FARGATE"

  network_configuration {
    subnets         = [aws_subnet.public_1.id]
    security_groups = [aws_security_group.app_sg.id]
    assign_public_ip = true
  }
}
`;
        break;
      }

      case 'serverless': {
        mainTf += `
# Serverless Function: ${data.name || node.id}
resource "aws_iam_role" "${resId}_lambda_role" {
  name = "${resId}_lambda_role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
    }]
  })
}

resource "aws_lambda_function" "${resId}" {
  function_name = "${resId}"
  role          = aws_iam_role.${resId}_lambda_role.arn
  handler       = "index.handler"
  runtime       = "nodejs20.x"
  memory_size   = ${config.memory || 512}
  timeout       = ${config.timeout || 15}

  filename         = "function_payload.zip"
  source_code_hash = filebase64sha256("function_payload.zip")
}
`;
        break;
      }

      case 'load_balancer': {
        mainTf += `
# Application Load Balancer: ${data.name || node.id}
resource "aws_lb" "${resId}" {
  name               = "${resId}-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.app_sg.id]
  subnets            = [aws_subnet.public_1.id]

  tags = {
    Name = "${data.name || node.id}"
  }
}

resource "aws_lb_target_group" "${resId}_tg" {
  name     = "${resId}-tg"
  port     = 80
  protocol = "HTTP"
  vpc_id   = aws_vpc.main.id
}
`;
        outputs.push({
          name: `${resId}_dns_name`,
          value: `aws_lb.${resId}.dns_name`,
          desc: `DNS name of ${data.name || node.id}`
        });
        break;
      }

      case 'api_gateway': {
        mainTf += `
# API Gateway: ${data.name || node.id}
resource "aws_api_gateway_rest_api" "${resId}" {
  name        = "${resId}_api"
  description = "API Gateway endpoint for ${data.name || node.id}"
}
`;
        break;
      }

      case 'cdn': {
        mainTf += `
# CloudFront CDN Distribution: ${data.name || node.id}
resource "aws_cloudfront_distribution" "${resId}" {
  enabled             = true
  is_ipv6_enabled     = true
  default_root_object = "index.html"

  origin {
    domain_name = "example.s3.amazonaws.com"
    origin_id   = "s3-${resId}"
  }

  default_cache_behavior {
    allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "s3-${resId}"

    forwarded_values {
      query_string = false
      cookies { forward = "none" }
    }

    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
  }

  restrictions {
    geo_restriction { restriction_type = "none" }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}
`;
        break;
      }

      case 'postgresql':
      case 'mysql': {
        const engine = nodeType === 'mysql' ? 'mysql' : 'postgres';
        const instClass = config.instanceType || 'db.t3.medium';
        mainTf += `
# Relational Database (${nodeType.toUpperCase()}): ${data.name || node.id}
resource "aws_db_instance" "${resId}" {
  allocated_storage     = ${config.storage || 100}
  max_allocated_storage = 500
  engine                = "${engine}"
  instance_class        = "${instClass}"
  db_name               = "${resId}_db"
  username              = "dbadmin"
  password              = var.db_password
  skip_final_snapshot   = true
  publicly_accessible   = false
  vpc_security_group_ids = [aws_security_group.app_sg.id]

  tags = {
    Name = "${data.name || node.id}"
  }
}
`;
        outputs.push({
          name: `${resId}_endpoint`,
          value: `aws_db_instance.${resId}.endpoint`,
          desc: `Endpoint connection string for ${data.name || node.id}`
        });
        break;
      }

      case 'redis': {
        const nodeTypeClass = config.nodeType || 'cache.t3.medium';
        mainTf += `
# Redis ElastiCache Cluster: ${data.name || node.id}
resource "aws_elasticache_cluster" "${resId}" {
  cluster_id           = "${resId}-redis"
  engine               = "redis"
  node_type            = "${nodeTypeClass}"
  num_cache_nodes      = 1
  parameter_group_name = "default.redis7"
  port                 = 6379
}
`;
        break;
      }

      case 'object_storage': {
        mainTf += `
# S3 Object Storage Bucket: ${data.name || node.id}
resource "aws_s3_bucket" "${resId}" {
  bucket        = "${projectName}-${resId}-bucket"
  force_destroy = true

  tags = {
    Name = "${data.name || node.id}"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "${resId}_crypto" {
  bucket = aws_s3_bucket.${resId}.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}
`;
        break;
      }

      case 'queue': {
        mainTf += `
# SQS Queue: ${data.name || node.id}
resource "aws_sqs_queue" "${resId}" {
  name                      = "${resId}-queue"
  delay_seconds             = 0
  max_message_size          = 262144
  message_retention_seconds = 86400
  visibility_timeout_seconds = 30
}
`;
        break;
      }

      case 'waf': {
        mainTf += `
# Web Application Firewall (WAF): ${data.name || node.id}
resource "aws_wafv2_web_acl" "${resId}" {
  name        = "${resId}-waf"
  description = "WAF protection rule group for ${data.name || node.id}"
  scope       = "REGIONAL"

  default_action {
    allow {}
  }

  visibility_config {
    cloudwatch_metrics_enabled = true
    metric_name                = "${resId}-waf-metrics"
    sampled_requests_enabled   = true
  }
}
`;
        break;
      }

      case 'kms': {
        mainTf += `
# KMS Encryption Key: ${data.name || node.id}
resource "aws_kms_key" "${resId}" {
  description             = "KMS Master Encryption Key for ${data.name || node.id}"
  deletion_window_in_days = 30
  enable_key_rotation     = true
}

resource "aws_kms_alias" "${resId}_alias" {
  name          = "alias/${resId}-key"
  target_key_id = aws_kms_key.${resId}.key_id
}
`;
        break;
      }

      case 'secrets_manager': {
        mainTf += `
# AWS Secrets Manager Vault: ${data.name || node.id}
resource "aws_secretsmanager_secret" "${resId}" {
  name                    = "${projectName}-${resId}-vault"
  kms_key_id              = aws_kms_key.${resId < nodes.length ? sanitizeName(nodes[0].data?.name || 'app') : 'app'}.key_id
  recovery_window_in_days = 7
}
`;
        break;
      }

      case 'iam_identity': {
        mainTf += `
# Cognito Identity User Pool: ${data.name || node.id}
resource "aws_cognito_user_pool" "${resId}" {
  name = "${projectName}-${resId}-pool"

  password_policy {
    minimum_length    = 12
    require_lowercase = true
    require_numbers   = true
    require_symbols   = true
    require_uppercase = true
  }
}
`;
        break;
      }

      case 'opensearch': {
        mainTf += `
# OpenSearch Search Cluster: ${data.name || node.id}
resource "aws_opensearch_domain" "${resId}" {
  domain_name    = "${resId}-domain"
  engine_version = "OpenSearch_2.11"

  cluster_config {
    instance_type  = "or1.medium.search"
    instance_count = ${config.dataNodes || 3}
  }

  ebs_options {
    ebs_enabled = true
    volume_size = ${config.storageGb || 200}
  }
}
`;
        break;
      }

      case 'kinesis_stream': {
        mainTf += `
# Kinesis Event Stream: ${data.name || node.id}
resource "aws_kinesis_stream" "${resId}" {
  name             = "${resId}-stream"
  shard_count      = ${config.shards || 4}
  retention_period = ${config.retentionHours || 24}
}
`;
        break;
      }

      case 'ai_inference': {
        mainTf += `
# SageMaker AI ML Inference Model: ${data.name || node.id}
resource "aws_sagemaker_endpoint_configuration" "${resId}_config" {
  name = "${resId}-endpoint-config"

  production_variants {
    variant_name           = "variant-1"
    model_name             = "llama3-7b-instruct"
    initial_instance_count = ${config.instanceCount || 1}
    instance_type          = "${config.instanceType || 'ml.g5.xlarge'}"
  }
}
`;
        break;
      }

      case 'cloudwatch_metrics': {
        mainTf += `
# CloudWatch Metric Alarm: ${data.name || node.id}
resource "aws_cloudwatch_metric_alarm" "${resId}_cpu_alarm" {
  alarm_name          = "${projectName}-high-cpu-alarm"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 2
  metric_name         = "CPUUtilization"
  namespace           = "AWS/EC2"
  period              = 120
  statistic           = "Average"
  threshold           = 85
}
`;
        break;
      }

      default:
        break;
    }
  });

  const variablesTf = `# Variables definition
variable "aws_region" {
  description = "Target AWS Region"
  type        = string
  default     = "${region}"
}

variable "ubuntu_ami_id" {
  description = "Ubuntu LTS AMI ID"
  type        = string
  default     = "ami-0c7217cdde317cfec"
}

variable "db_password" {
  description = "Database master password"
  type        = string
  sensitive   = true
  default     = "SuperSecretPass123!"
}
`;

  let outputsTf = `# Terraform Outputs\n`;
  outputs.forEach((out) => {
    outputsTf += `
output "${out.name}" {
  description = "${out.desc}"
  value       = ${out.value}
}
`;
  });

  return { mainTf, variablesTf, outputsTf };
}

/**
 * Generate AWS CloudFormation YAML format
 */
export function generateCloudFormationCode(nodes = [], edges = [], options = {}) {
  const projectName = sanitizeName(options.projectName || 'InfrasaasApp', 'InfrasaasApp');

  let cfYaml = `AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CloudFormation Architecture Template
  Auto-generated by InfraSaaS (https://infrasaas.app)
  Project: ${options.projectName || 'Cloud Architecture'}

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    Description: Environment stage name

Resources:
  # VPC Infrastructure
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub \${AWS::StackName}-VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub \${AWS::StackName}-PublicSubnet

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for app tier
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

`;

  nodes.forEach((node) => {
    if (node.type === 'client') return;
    const data = node.data || {};
    const config = data.config || {};
    const nodeType = data.type || '';
    const resId = sanitizeName(data.name || node.id, 'Resource').replace(/_/g, '');

    switch (nodeType) {
      case 'server':
      case 'vm': {
        cfYaml += `  ${resId}Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: ${config.instanceType || 't3.medium'}
      ImageId: ami-0c7217cdde317cfec
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      Tags:
        - Key: Name
          Value: ${data.name || node.id}

`;
        break;
      }
      case 'object_storage': {
        cfYaml += `  ${resId}Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub \${AWS::StackName}-${resId.toLowerCase()}-vault
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

`;
        break;
      }
      case 'postgresql':
      case 'mysql': {
        cfYaml += `  ${resId}DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: ${config.instanceType || 'db.t3.medium'}
      Engine: ${nodeType === 'mysql' ? 'mysql' : 'postgres'}
      AllocatedStorage: '${config.storage || 100}'
      MasterUsername: dbadmin
      MasterUserPassword: TempDBPassword123!
      VPCSecurityGroups:
        - !Ref AppSecurityGroup

`;
        break;
      }
      case 'queue': {
        cfYaml += `  ${resId}Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${resId.toLowerCase()}-queue

`;
        break;
      }
      default:
        break;
    }
  });

  return cfYaml;
}
